name: Generate static content using 11ty
on: push
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: 'get repo'
        uses: actions/checkout@v3

      - name: 'setup Node'
        uses: actions/setup-node@v3
        with:
          node-version: current

      - name: 'cache node_modules'
        uses: actions/cache@v3
        with:
          path: 'node_modules'
          key: ${{ hashFiles('package-lock.json') }}

      - name: 'install dependencies'
        run: npm install

      - name: 'generate content'
        run: npm ci

      - name: 'upload artificat'
        if: github.ref_name == 'main'
        uses: actions/upload-pages-artifact@v1
